Repository reactivemarbles/DynamicData, pull requests merged in 2024-02, with the labels that each got.

#845 Feature: Leverage TransformImmutable
  src/DynamicData.Tests/Cache/MergeManyChangeSetsCacheSourceCompareFixture.cs
  src/DynamicData/Cache/Internal/FilterOnObservable.cs
  src/DynamicData/Cache/Internal/MergeManyCacheChangeSetsSourceCompare.cs
Labels: enhancement

#844 Feature: Use Flag instead of Counter for TransformManyAsync/TransformOnObservable
  src/DynamicData/Cache/Internal/MergeChangeSets.cs
  src/DynamicData/Cache/Internal/MergeMany.cs
  src/DynamicData/Cache/Internal/MergeManyCacheChangeSets.cs
  src/DynamicData/Cache/Internal/MergeManyCacheChangeSetsSourceCompare.cs
  src/DynamicData/Cache/Internal/MergeManyListChangeSets.cs
  src/DynamicData/Cache/Internal/TransformManyAsync.cs
  src/DynamicData/Cache/Internal/TransformOnObservable.cs
  src/DynamicData/Internal/ObservableEx.cs
Labels: enhancement

#843 Removed unused files previously used by testing for older .NET targets.
  src/DynamicData.Tests/API/ApiApprovalTests.DynamicDataTests.DotNet6_0.verified.txt
  src/DynamicData.Tests/API/ApiApprovalTests.DynamicDataTests.DotNet7_0.verified.txt
Labels: Housekeeping

#847 Feature: GroupOnObservable Operator
  src/DynamicData.Tests/API/ApiApprovalTests.DynamicDataTests.DotNet8_0.verified.txt
  src/DynamicData.Tests/Cache/GroupOnObservableFixture.cs
  src/DynamicData.Tests/Cache/GroupOnPropertyFixture.cs
  src/DynamicData.Tests/Domain/Fakers.cs
  src/DynamicData.Tests/Domain/Person.cs
  src/DynamicData/Cache/Internal/DynamicGrouper.cs
  src/DynamicData/Cache/Internal/GroupOnObservable.cs
  src/DynamicData/Cache/ObservableCacheEx.cs
  src/DynamicData/Cache/Tests/GroupChangeSetAggregator.cs
  src/DynamicData/Cache/Tests/TestEx.cs
Labels: enhancement

#849 Feature: Group by Dynamic Selector Function
  src/DynamicData.Tests/API/ApiApprovalTests.DynamicDataTests.DotNet8_0.verified.txt
  src/DynamicData.Tests/Cache/GroupOnDynamicFixture.cs
  src/DynamicData.Tests/Cache/GroupOnObservableFixture.cs
  src/DynamicData.Tests/Cache/MergeManyChangeSetsCacheSourceCompareFixture.cs
  src/DynamicData.Tests/Domain/Fakers.cs
  src/DynamicData.Tests/Domain/Person.cs
  src/DynamicData/Cache/Internal/DynamicGrouper.cs
  src/DynamicData/Cache/Internal/GroupOnDynamic.cs
  src/DynamicData/Cache/Internal/GroupOnObservable.cs
  src/DynamicData/Cache/ObservableCacheEx.cs
  src/DynamicData/Cache/Tests/GroupChangeSetAggregator.cs
  src/DynamicData/Internal/ObservableEx.cs
Labels: enhancement

#852 Feature: SuspendNotifications Methods for SourceCache / IntermediateCache
  src/DynamicData.Tests/API/ApiApprovalTests.DynamicDataTests.DotNet8_0.verified.txt
  src/DynamicData.Tests/Cache/SuspendNotificationsFixture.cs
  src/DynamicData/Cache/IntermediateCache.cs
  src/DynamicData/Cache/Internal/ReaderWriter.cs
  src/DynamicData/Cache/ObservableCache.cs
  src/DynamicData/Cache/SourceCache.cs
Labels: enhancement

#863 Bug Fix: Consolidate changes made to Group Caches into a single ChangeSet
  src/DynamicData.Tests/Cache/GroupOnDynamicFixture.cs
  src/DynamicData.Tests/Cache/GroupOnObservableFixture.cs
  src/DynamicData/Cache/Internal/DynamicGrouper.cs
  src/DynamicData/Cache/Internal/GroupOn.cs
  src/DynamicData/Cache/Internal/ManagedGroup.cs
Labels: bug

#862 Maintenance: Centralized Value for Default IScheduler instance
  src/DynamicData/Cache/Internal/AutoRefresh.cs
  src/DynamicData/Cache/Internal/BatchIf.cs
  src/DynamicData/Cache/Internal/GroupOnProperty.cs
  src/DynamicData/Cache/Internal/GroupOnPropertyWithImmutableState.cs
  src/DynamicData/Cache/Internal/ToObservableChangeSet.cs
  src/DynamicData/Cache/ObservableCacheEx.cs
  src/DynamicData/Experimental/ExperimentalEx.cs
  src/DynamicData/GlobalConfig.cs
  src/DynamicData/List/Internal/AutoRefresh.cs
  src/DynamicData/List/Internal/BufferIf.cs
  src/DynamicData/List/Internal/FilterOnObservable.cs
  src/DynamicData/List/Internal/GroupOnProperty.cs
  src/DynamicData/List/Internal/GroupOnPropertyWithImmutableState.cs
  src/DynamicData/List/Internal/ToObservableChangeSet.cs
  src/DynamicData/List/ObservableListEx.cs
Labels: Housekeeping

#868 ExpireAfter Redesign
  .editorconfig
  src/DynamicData.Benchmarks/Cache/ExpireAfter_Cache_ForSource.cs
  src/DynamicData.Benchmarks/Cache/ExpireAfter_Cache_ForStream.cs
  src/DynamicData.Benchmarks/DynamicData.Benchmarks.csproj
  src/DynamicData.Benchmarks/List/ExpireAfter_List.cs
  src/DynamicData.Tests/Cache/ExpireAfterFixture.ForSource.cs
  src/DynamicData.Tests/Cache/ExpireAfterFixture.ForStream.cs
  src/DynamicData.Tests/Cache/ExpireAfterFixture.cs
  src/DynamicData.Tests/List/ExpireAfterFixture.cs
  src/DynamicData.Tests/Utilities/FakeScheduler.cs
  src/DynamicData.Tests/Utilities/TestSourceCache.cs
  src/DynamicData.Tests/Utilities/TestSourceList.cs
  src/DynamicData/Cache/Internal/ExpireAfter.ForSource.cs
  src/DynamicData/Cache/Internal/ExpireAfter.ForStream.cs
  src/DynamicData/Cache/Internal/TimeExpirer.cs
  src/DynamicData/Cache/ObservableCacheEx.cs
  src/DynamicData/DynamicData.csproj
  src/DynamicData/List/Internal/ExpireAfter.cs
  src/DynamicData/List/ObservableListEx.cs
  src/DynamicData/Polyfills/ListEnsureCapacity.cs
Labels: bug, enhancement, Performance

#865 Feature: OfType Operator
  src/DynamicData.Tests/API/ApiApprovalTests.DynamicDataTests.DotNet8_0.verified.txt
  src/DynamicData.Tests/Cache/OfTypeFixture.cs
  src/DynamicData.Tests/Utilities/ObservableSpy.cs
  src/DynamicData/Cache/Internal/OfType.cs
  src/DynamicData/Cache/ObservableCacheEx.cs
Labels: enhancement
