Repository reactivemarbles/DynamicData, pull requests merged in 2024-06, with the labels that each got.

#874 [DO NOT MERGE]: IKeyValueCollection as IReadOnlyList
  src/DynamicData.Tests/API/ApiApprovalTests.DynamicDataTests.DotNet8_0.verified.txt
  src/DynamicData.Tests/Cache/SortFixture.cs
  src/DynamicData/Cache/IKeyValueCollection.cs
Labels: enhancement, breaking change

#822 Fixed ambiguous overloads for `ObservableCacheEx.ExpireAfter()` and `ObservableListEx.ExpireAfter()`.
  src/DynamicData.Benchmarks/Cache/ExpireAfter_Cache_ForSource.cs
  src/DynamicData.Tests/API/ApiApprovalTests.DynamicDataTests.DotNet8_0.verified.txt
  src/DynamicData.Tests/Cache/ExpireAfterFixture.ForSource.cs
  src/DynamicData/Cache/ObservableCacheEx.cs
  src/DynamicData/List/ObservableListEx.cs
Labels: bug, breaking change

#912 IObservableList items as IReadOnlyList
  src/DynamicData.Tests/API/ApiApprovalTests.DynamicDataTests.DotNet8_0.verified.txt
  src/DynamicData.Tests/Binding/AvaloniaDictionaryFixture.cs
  src/DynamicData.Tests/Binding/BindingListToChangeSetFixture.cs
  src/DynamicData.Tests/Binding/IObservableListBindCacheFixture.cs
  src/DynamicData.Tests/Binding/IObservableListBindCacheSortedFixture.cs
  src/DynamicData.Tests/Binding/IObservableListBindListFixture.cs
  src/DynamicData.Tests/Binding/ObservableCollectionExtendedToChangeSetFixture.cs
  src/DynamicData.Tests/Binding/ObservableCollectionToChangeSetFixture.cs
  src/DynamicData.Tests/Binding/ReadOnlyObservableCollectionToChangeSetFixture.cs
  src/DynamicData.Tests/Cache/MergeManyChangeSetsListFixture.cs
  src/DynamicData.Tests/Cache/TransformManyAsyncFixture.cs
  src/DynamicData.Tests/EnumerableIListFixture.cs
  src/DynamicData.Tests/List/AutoRefreshFixture.cs
  src/DynamicData.Tests/List/DisposeManyFixture.cs
  src/DynamicData.Tests/List/DistinctValuesFixture.cs
  src/DynamicData.Tests/List/DynamicOrFixture.cs
  src/DynamicData.Tests/List/DynamicXOrFixture.cs
  src/DynamicData.Tests/List/FilterControllerFixtureWithClearAndReplace.cs
  src/DynamicData.Tests/List/FilterControllerFixtureWithDiffSet.cs
  src/DynamicData.Tests/List/FilterFixture.cs
  src/DynamicData.Tests/List/FilterWithObservable.cs
  src/DynamicData.Tests/List/GroupImmutableFixture.cs
  src/DynamicData.Tests/List/GroupOnFixture.cs
  src/DynamicData.Tests/List/GroupOnPropertyFixture.cs
  src/DynamicData.Tests/List/GroupOnPropertyWithImmutableStateFixture.cs
  src/DynamicData.Tests/List/MergeChangeSetsFixture.cs
  src/DynamicData.Tests/List/MergeManyChangeSetsCacheFixture.cs
  src/DynamicData.Tests/List/MergeManyChangeSetsListFixture.cs
  src/DynamicData.Tests/List/OrFixture.cs
  src/DynamicData.Tests/List/SelectFixture.cs
  src/DynamicData.Tests/List/SizeLimitFixture.cs
  src/DynamicData.Tests/List/SortFixture.cs
  src/DynamicData.Tests/List/SortMutableFixture.cs
  src/DynamicData.Tests/List/SubscribeManyFixture.cs
  src/DynamicData.Tests/List/TransformAsyncFixture.cs
  src/DynamicData.Tests/List/TransformFixture.cs
  src/DynamicData.Tests/List/XOrFixture.cs
  src/DynamicData.Tests/Utilities/TestSourceList.cs
  src/DynamicData/List/IObservableList.cs
  src/DynamicData/List/Internal/AnonymousObservableList.cs
  src/DynamicData/List/SourceList.cs
Labels: enhancement, breaking change

#911 use null check pattern
  src/DynamicData/Cache/Internal/ExpireAfter.ForSource.cs
  src/DynamicData/Cache/Internal/ExpireAfter.ForStream.cs
  src/DynamicData/Cache/Internal/FilterImmutable.cs
  src/DynamicData/Cache/Internal/OfType.cs
  src/DynamicData/Cache/Internal/ToObservableChangeSet.cs
  src/DynamicData/Cache/Internal/ToObservableOptional.cs
  src/DynamicData/List/Internal/ExpireAfter.cs
  src/DynamicData/List/Internal/ToObservableChangeSet.cs
  src/DynamicData/List/Internal/Transformer.cs
Labels: Housekeeping

#910 fix polyfills visibility
  src/DynamicData/DynamicData.csproj
  src/DynamicData/Polyfills/CompilerFeatureRequiredAttribute.cs
  src/DynamicData/Polyfills/IsExternalInit.cs
  src/DynamicData/Polyfills/ListEnsureCapacity.cs
  src/DynamicData/Polyfills/RequiredMemberAttribute.cs
Labels: Housekeeping
